name: Build and Install Statediff with Spack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true  # This ensure that the statediff submodule is fetched

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Add Spack repository
        run: spack repo add ./spack-repo

      - name: Create Spack Environment
        shell: spack-bash {0}
        run: |
          spack env create statediff-env
          spack env activate statediff-env
          spack add statediff@v0.1
          spack concretize

      - name: Install Statediff
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack install

      - name: Verify Statediff Installation
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack find

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Load Spack environment
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env

      - name: Run tests
        shell: spack-bash {0}
        run: ./test.sh