name: Build and Install Statediff with Spack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true  # Ensure submodules are fetched if needed

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Add and Debug Custom Spack Repo
        shell: spack-bash {0}
        run: |
          echo "==> Remove any existing repo with namespace 'statediff'"
          spack repo rm statediff || true

          echo "==> Add custom repo"
          spack repo add ./spack-repo

          echo "==> Show repo list"
          spack repo list

          echo "==> Show spack debug report"
          spack debug report

          echo "==> List contents of spack-repo"
          tree ./spack-repo || echo "tree failed"

          echo "==> Show repo.yaml"
          cat ./spack-repo/repo.yaml || echo "repo.yaml missing!"

          echo "==> Show package.py"
          cat ./spack-repo/packages/statediff/package.py || echo "package.py missing!"

          echo "==> Clean Spack cache"
          spack clean -a

          echo "==> Try listing statediff"
          spack list | grep statediff || echo "statediff not found in 'spack list'"

          echo "==> Try info on 'statediff'"
          spack info statediff || echo "spack info statediff failed"

          echo "==> Try info on namespaced 'statediff.statediff'"
          spack info statediff.statediff || echo "spack info statediff.statediff failed"

          echo "==> Try manual Python import"
          export PYTHONPATH=$SPACK_ROOT/lib/spack:$PYTHONPATH
          python3 -c "import spack.pkg.statediff.statediff" || echo "Manual import failed"


      - name: Debug Spack Package Detection
        shell: spack-bash {0}
        run: |
          spack repo list
          spack list | grep statediff || echo "statediff package not found!"
          spack spec statediff@main || echo "statediff package not recognized!"

      - name: Create and Activate Spack Environment
        shell: spack-bash {0}
        run: |
          spack env create statediff-env || echo "Environment creation failed!"
          spack env activate statediff-env
          spack add statediff@main  # Y\Updated to match package.py
          spack concretize

      - name: Install Statediff
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack install || echo "Spack installation failed!"

      - name: Verify Statediff Installation
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack find

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Ensure Spack environment exists
        shell: spack-bash {0}
        run: |
          if ! spack env list | grep -q "^statediff-env$"; then
            echo "Spack environment 'statediff-env' not found. Creating it..."
            spack env create statediff-env
          else
            echo "Spack environment 'statediff-env' already exists."
          fi
          spack add statediff@main
          spack concretize

      - name: Load Spack environment
        shell: spack-bash {0}
        run: spack env activate statediff-env

      - name: Run tests
        shell: spack-bash {0}
        run: bash ./tests/statediff/test.sh
