name: Build and Install Statediff with Spack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          path: spack

      - name: Add and Debug Custom Spack Repository
        shell: bash
        run: |
          echo "Cleaning any previous state..."
          spack repo rm statediff || true
          spack repo add ./spack-repo
          spack repo list
          spack clean -a

      - name: Confirm Package Detection
        shell: spack-bash {0}
        run: |
          echo "==> REPO LIST"
          spack repo list

          echo "==> CHECK PACKAGE LISTING"
          spack list | grep statediff || echo "statediff not found"

          echo "==> SHOW PACKAGE INFO"
          spack info statediff || echo "spack info statediff failed"

          echo "==> CHECK PYTHON IMPORT"
          python3 -c "import spack.pkg.statediff.statediff" && echo "Python import succeeded" || echo "Python import failed"

      - name: Create and Install Environment
        shell: spack-bash {0}
        run: |
          echo "Creating environment"
          spack env create statediff-env
          spack env activate statediff-env

          echo "Adding statediff to env"
          spack add statediff@main
          spack concretize

          echo "Installing"
          spack install

      - name: Verify Installation
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack find