name: Build and Install Statediff with Spack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true  # Ensure submodules are fetched if needed

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Add Spack Repository and Clear Cache
        run: |
          spack repo add ./spack-repo
          spack clean -m  # Clears Spack's module cache to ensure new packages are found

      - name: Debug Spack Packages (Check If Statediff Exists)
        run: |
          spack repo list
          spack list | grep statediff || echo "statediff package not found!"
          ls -R ./spack-repo/packages/statediff || echo "package.py not found!"

      - name: Debug Concretization Before Environment Setup
        run: |
          spack spec statediff@v0.1 || echo "statediff package not recognized!"

      - name: Create and Activate Spack Environment
        shell: spack-bash {0}
        run: |
          spack env create statediff-env || echo "Environment creation failed!"
          spack env activate statediff-env
          spack add statediff@v0.1
          spack concretize

      - name: Install Statediff
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack install || echo "Spack installation failed!"

      - name: Verify Statediff Installation
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env
          spack find

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout state-diff repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          path: spack

      - name: Load Spack environment
        shell: spack-bash {0}
        run: |
          spack env activate statediff-env

      - name: Run tests
        shell: spack-bash {0}
        run: ./test.sh