name: CI - C++ Build with Spack (Kokkos)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build git

      - name: Clone and bootstrap Spack
        run: |
          git clone https://github.com/spack/spack.git $HOME/spack
          echo ". $HOME/spack/share/spack/setup-env.sh" >> $GITHUB_ENV

      - name: Install Kokkos with Spack
        run: |
          . $HOME/spack/share/spack/setup-env.sh
          spack install kokkos +serial build_type=Release
          spack find --paths kokkos
          KOKKOS_DIR=$(spack location -i kokkos)
          echo "KOKKOS_DIR=$KOKKOS_DIR" >> $GITHUB_ENV

      - name: Configure state-diff with Spack-managed Kokkos
        run: |
          mkdir -p build && cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fPIC" \
            -DENABLE_TESTS=ON \
            -DKokkos_DIR=$KOKKOS_DIR/lib64/cmake/Kokkos \
            ../external/state-diff

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
